# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  CloudAgentPool

steps:
- script: echo Hello, world_cloud
  displayName: 'Run a one-line script'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Cloudconnect'
    backendAzureRmResourceGroupName: 'DevOpsRG'
    backendAzureRmStorageAccountName: 'devopstorage121'
    backendAzureRmContainerName: 'devopscontainer'
    backendAzureRmKey: 'cloudconnect.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Cloudconnect'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Cloudconnect'