# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  CICD AGENT POOL

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'DevOps Service Connect'
    backendAzureRmStorageAccountName: 'devopstorage121'
    backendAzureRmContainerName: 'devopscontainer'
    backendAzureRmKey: 'learndevops.tfstate'